name: Build RealTimeSRT

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libglib2.0-0
      - name: Clean environment 
        run: |
          pip cache purge || true
          rm -rf ~/.cache/* || true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Linux binary
        env:
          CT2_FORCE_CPU: "1"
        run: |
          pyinstaller \
          --onefile \
          --windowed \
          --name realTimeSRT-linux \
          --collect-all PyQt5 \
          --collect-all vosk \
          --hidden-import=vosk \
          --add-data "bin/linux/ffmpeg:bin/linux/ffmpeg" \
          main.py
      - name: Set executable permission
        run: |
          chmod 755 dist/realTimeSRT-linux
          ls -lah dist/
          file dist/realTimeSRT-linux
      - name: Package Linux binary
        run: |
          tar -czf realTimeSRT-linux-linux-x64.tar.gz -C dist realTimeSRT-linux

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: realTimeSRT-linux-linux-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Windows exe
        run: |
          pyinstaller `
          --onefile `
          --windowed `
          --name realTimeSRT-windows `
          --collect-all PyQt5 `
          --collect-all vosk `
          --hidden-import=vosk `
          --add-data "bin/windows/ffmpeg.exe;bin" `
          main.py

      - name: Upload realTimeSRT Windows to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/realTimeSRT-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}

  build-macos-x64:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Intel macOS binary
        run: |          
          pyinstaller \
            --onefile \
            --windowed \
            --name realTimeSRT-macos-x64 \
            --collect-all PyQt5 \
            --collect-all vosk \
            --hidden-import=vosk \
            --add-data "bin/macos/ffmpeg:bin" \
            main.py

      - name: Verify binary
        run: |
          chmod 755 dist/realTimeSRT-macos-x64
          file dist/realTimeSRT-macos-x64
          ls -lah dist/

      - name: Package binary
        run: |
          tar -czf realTimeSRT-macos-x64.tar.gz -C dist realTimeSRT-macos-x64

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: realTimeSRT-macos-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}


  build-macos-arm64:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Apple Silicon macOS binary
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name realTimeSRT-macos-arm64 \
            --collect-all PyQt5 \
            --collect-all vosk \
            --hidden-import=vosk \
            --add-data "bin/macos/ffmpeg:bin" \
            main.py

      - name: Verify binary
        run: |
          chmod 755 dist/realTimeSRT-macos-arm64
          file dist/realTimeSRT-macos-arm64
          ls -lah dist/

      - name: Package binary
        run: |
          tar -czf realTimeSRT-macos-arm64.tar.gz -C dist realTimeSRT-macos-arm64

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: realTimeSRT-macos-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GTH_TOKEN }}
